name: update
on:
  workflow_dispatch:
    inputs:
      update_charts:
        description: Render charts and animations during this manual run
        required: true
        type: boolean
        default: true
  schedule:
    - cron: "0 2 * * *"
    - cron: "0 14 * * *"
concurrency:
  group: ${{ github.ref }}
jobs:
  run:
    name: Update data
    runs-on: the-economist-war-fire-model
    container:
      image: ghcr.io/theeconomist/the-economist-war-fire-model:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        env:
          GIT_LFS_SKIP_SMUDGE: "1"
        with:
          lfs: false
          fetch-depth: 2          # shallow, with enough history for the rebase below
          clean: true             # <- remove working tree junk
      - name: Pull required LFS files
        run: |
          git -C "$GITHUB_WORKSPACE" lfs install --local --skip-smudge
          git -C "$GITHUB_WORKSPACE" lfs pull --exclude="output-data/model-objects/boot_predictions*,output-data/model-objects/stable_covariates.csv,source-data/firms-imports/2000-2022/**,output-data/war_fires_by_ADM3.csv"
      - name: Run R script
        run: |
          . /opt/conda/etc/profile.d/conda.sh && conda activate base
          Rscript -e "source('scripts/000-autoupdater.R')"
        shell: bash
        env:
          FIRMS_API_KEY: ${{ secrets.FIRMS_API_KEY }}
          UPDATE_CHARTS_AND_ANIMATIONS: ${{ (github.event_name == 'workflow_dispatch' && inputs.update_charts) || github.event.schedule == '0 2 * * *' }}
  
      - name: Commit changes
        run: |
          git config --global --add safe.directory /__w/the-economist-war-fire-model/the-economist-war-fire-model

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add output-data/model-objects output-data/firms-clipped
          git commit --allow-empty -m "Data auto-update" -a

          git pull --rebase origin "$TARGET_BRANCH"
          git push origin "HEAD:$TARGET_BRANCH"
        env:
          TARGET_BRANCH: ${{ github.ref_name }}

      - name: Report failure
        if: failure()
        run: |
          curl -X POST -H "Content-type: application/json" --data '{ "channel":"${{ secrets.SLACK_CHANNEL }}", "text":":x: <@UTBFTA7Q9> <@U02N72XERFW> The Economist War Fire Model failed to update. Please check the logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}", "unfurl_links": false }' ${{ secrets.SLACK_WEBHOOK }}

          
